/** Conversation session status */
export type ConversationStatus = 'active' | 'escalated' | 'closed';

/** Conversation scenario for system prompt injection */
export type ConversationScenario =
  | 'installation'
  | 'training'
  | 'configuration_pack'
  | 'general';

/** Rich element types for AI responses */
export type RichElementType = 'card' | 'button' | 'code_block' | 'service_plan_card';

/** Rich element in AI response */
export interface RichElement {
  type: RichElementType;
  data: Record<string, unknown>;
}

/** Action suggestion in AI response */
export interface SuggestedAction {
  label: string;
  action: string;
  payload?: Record<string, unknown>;
}

/** Service requirements collected during conversation */
export interface ServiceRequirements {
  deviceEnvironment?: string;
  operatingSystem?: string;
  networkEnvironment?: string;
  useCase?: string;
  preferredServiceTime?: string;
}

/** Service plan card generated by AI */
export interface ServicePlanCard {
  tier: 'standard' | 'professional' | 'enterprise';
  price: number;
  currency: string;
  ocsasLevel: 1 | 2 | 3;
  estimatedDuration: number;
  serviceContent: string[];
  warrantyDays: number;
  includesTokenHub: boolean;
}

/** Create session request */
export interface CreateSessionDto {
  userId: string;
  language?: string;
  scenario?: ConversationScenario;
}

/** Send message request */
export interface SendMessageDto {
  content: string;
}

/** AI response from concierge */
export interface AIResponse {
  content: string;
  richElements?: RichElement[];
  suggestedActions?: SuggestedAction[];
  needsEscalation: boolean;
  collectedInfo?: Partial<ServiceRequirements>;
}

/** Escalation request */
export interface EscalateRequest {
  reason: string;
}

/** Escalation result */
export interface EscalationResult {
  sessionId: string;
  agentId: string;
  reason: string;
  language: string;
  scenario: ConversationScenario;
  conversationHistory: Array<{ role: string; content: string }>;
  collectedRequirements: Partial<ServiceRequirements> | null;
}
