/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    orders: Order;
    payments: Payment;
    'install-orders': InstallOrder;
    'delivery-reports': DeliveryReport;
    'service-reviews': ServiceReview;
    'hardware-products': HardwareProduct;
    'audit-logs': AuditLog;
    media: Media;
    'business-dictionary': BusinessDictionary;
    'data-dictionary': DataDictionary;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    'install-orders': InstallOrdersSelect<false> | InstallOrdersSelect<true>;
    'delivery-reports': DeliveryReportsSelect<false> | DeliveryReportsSelect<true>;
    'service-reviews': ServiceReviewsSelect<false> | ServiceReviewsSelect<true>;
    'hardware-products': HardwareProductsSelect<false> | HardwareProductsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'business-dictionary': BusinessDictionarySelect<false> | BusinessDictionarySelect<true>;
    'data-dictionary': DataDictionarySelect<false> | DataDictionarySelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('zh' | 'en' | 'ja' | 'ko' | 'de' | 'fr' | 'es')
    | ('zh' | 'en' | 'ja' | 'ko' | 'de' | 'fr' | 'es')[];
  globals: {
    'site-settings': SiteSetting;
    'pricing-config': PricingConfig;
    'ocsas-standards': OcsasStandard;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'pricing-config': PricingConfigSelect<false> | PricingConfigSelect<true>;
    'ocsas-standards': OcsasStandardsSelect<false> | OcsasStandardsSelect<true>;
  };
  locale: 'zh' | 'en' | 'ja' | 'ko' | 'de' | 'fr' | 'es';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  displayName?: string | null;
  avatarUrl?: (number | null) | Media;
  languagePreference?: ('zh' | 'en' | 'ja' | 'ko' | 'de' | 'fr' | 'es') | null;
  timezone?: string | null;
  region?: ('apac' | 'na' | 'eu') | null;
  role: 'admin' | 'certified_engineer' | 'individual_user';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber?: string | null;
  user: number | User;
  status: 'pending_payment' | 'paid' | 'dispatched' | 'accepted' | 'in_progress' | 'completed' | 'cancelled';
  totalAmount: number;
  currency?: string | null;
  region?: ('apac' | 'na' | 'eu') | null;
  product?: (number | null) | HardwareProduct;
  serviceTier?: ('standard' | 'professional' | 'enterprise') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hardware-products".
 */
export interface HardwareProduct {
  id: number;
  category: 'clawbox_lite' | 'clawbox_pro' | 'clawbox_enterprise' | 'recommended_hardware' | 'accessories';
  name: string;
  description: string;
  specs:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  price: number;
  stockByRegion?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  order: number | Order;
  amount: number;
  currency?: string | null;
  status: 'pending' | 'succeeded' | 'failed' | 'refunded';
  stripeSessionId?: string | null;
  stripePaymentIntentId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "install-orders".
 */
export interface InstallOrder {
  id: number;
  order: number | Order;
  serviceTier: 'standard' | 'professional' | 'enterprise';
  ocsasLevel: number;
  engineer?: (number | null) | User;
  installStatus: 'pending_dispatch' | 'accepted' | 'in_progress' | 'pending_acceptance' | 'completed';
  acceptedAt?: string | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "delivery-reports".
 */
export interface DeliveryReport {
  id: number;
  installOrder: number | InstallOrder;
  checklist:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  configItems:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  testResults:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  screenshots?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-reviews".
 */
export interface ServiceReview {
  id: number;
  order: number | Order;
  user: number | User;
  overallRating: number;
  attitudeRating?: number | null;
  skillRating?: number | null;
  comment?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  user?: (number | null) | User;
  action: string;
  resourceType: string;
  resourceId?: string | null;
  details?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  ipAddress?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-dictionary".
 */
export interface BusinessDictionary {
  id: number;
  category:
    | 'order_status'
    | 'install_status'
    | 'service_tier'
    | 'user_role'
    | 'region'
    | 'product_category'
    | 'payment_status'
    | 'ocsas_level';
  /**
   * 唯一标识符，如 order_status.pending_payment
   */
  key: string;
  /**
   * 显示名称（支持多语言）
   */
  label: string;
  /**
   * 详细描述（支持多语言）
   */
  description?: string | null;
  /**
   * 对应的系统值
   */
  value?: string | null;
  sortOrder?: number | null;
  isActive?: boolean | null;
  /**
   * 额外的元数据（如颜色、图标等）
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-dictionary".
 */
export interface DataDictionary {
  id: number;
  tableName:
    | 'users'
    | 'orders'
    | 'payments'
    | 'install-orders'
    | 'delivery-reports'
    | 'service-reviews'
    | 'hardware-products'
    | 'business-dictionary'
    | 'audit-logs';
  /**
   * 字段名称
   */
  fieldName: string;
  /**
   * 字段显示名（支持多语言）
   */
  fieldLabel: string;
  fieldType: 'text' | 'number' | 'date' | 'boolean' | 'enum' | 'relationship' | 'json' | 'richtext' | 'upload';
  /**
   * 字段说明（支持多语言）
   */
  fieldDescription?: string | null;
  isRequired?: boolean | null;
  /**
   * 是否支持多语言
   */
  isLocalized?: boolean | null;
  /**
   * 枚举选项（当字段类型为枚举时）
   */
  enumOptions?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 默认值
   */
  defaultValue?: string | null;
  /**
   * 验证规则（如 min, max, pattern 等）
   */
  validation?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'install-orders';
        value: number | InstallOrder;
      } | null)
    | ({
        relationTo: 'delivery-reports';
        value: number | DeliveryReport;
      } | null)
    | ({
        relationTo: 'service-reviews';
        value: number | ServiceReview;
      } | null)
    | ({
        relationTo: 'hardware-products';
        value: number | HardwareProduct;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'business-dictionary';
        value: number | BusinessDictionary;
      } | null)
    | ({
        relationTo: 'data-dictionary';
        value: number | DataDictionary;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  avatarUrl?: T;
  languagePreference?: T;
  timezone?: T;
  region?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  user?: T;
  status?: T;
  totalAmount?: T;
  currency?: T;
  region?: T;
  product?: T;
  serviceTier?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  order?: T;
  amount?: T;
  currency?: T;
  status?: T;
  stripeSessionId?: T;
  stripePaymentIntentId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "install-orders_select".
 */
export interface InstallOrdersSelect<T extends boolean = true> {
  order?: T;
  serviceTier?: T;
  ocsasLevel?: T;
  engineer?: T;
  installStatus?: T;
  acceptedAt?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "delivery-reports_select".
 */
export interface DeliveryReportsSelect<T extends boolean = true> {
  installOrder?: T;
  checklist?: T;
  configItems?: T;
  testResults?: T;
  screenshots?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-reviews_select".
 */
export interface ServiceReviewsSelect<T extends boolean = true> {
  order?: T;
  user?: T;
  overallRating?: T;
  attitudeRating?: T;
  skillRating?: T;
  comment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hardware-products_select".
 */
export interface HardwareProductsSelect<T extends boolean = true> {
  category?: T;
  name?: T;
  description?: T;
  specs?: T;
  price?: T;
  stockByRegion?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  user?: T;
  action?: T;
  resourceType?: T;
  resourceId?: T;
  details?: T;
  ipAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-dictionary_select".
 */
export interface BusinessDictionarySelect<T extends boolean = true> {
  category?: T;
  key?: T;
  label?: T;
  description?: T;
  value?: T;
  sortOrder?: T;
  isActive?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-dictionary_select".
 */
export interface DataDictionarySelect<T extends boolean = true> {
  tableName?: T;
  fieldName?: T;
  fieldLabel?: T;
  fieldType?: T;
  fieldDescription?: T;
  isRequired?: T;
  isLocalized?: T;
  enumOptions?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  defaultValue?: T;
  validation?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  platformName?: string | null;
  logoUrl?: string | null;
  defaultLanguage?: ('zh' | 'en' | 'ja' | 'ko' | 'de' | 'fr' | 'es') | null;
  contactEmail?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-config".
 */
export interface PricingConfig {
  id: number;
  installationPricing?: {
    standard?: number | null;
    professional?: number | null;
    enterprise?: number | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ocsas-standards".
 */
export interface OcsasStandard {
  id: number;
  levels?:
    | {
        level: number;
        name: string;
        description?: string | null;
        checklistItems?:
          | {
              item: string;
              category?: string | null;
              required?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  platformName?: T;
  logoUrl?: T;
  defaultLanguage?: T;
  contactEmail?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-config_select".
 */
export interface PricingConfigSelect<T extends boolean = true> {
  installationPricing?:
    | T
    | {
        standard?: T;
        professional?: T;
        enterprise?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ocsas-standards_select".
 */
export interface OcsasStandardsSelect<T extends boolean = true> {
  levels?:
    | T
    | {
        level?: T;
        name?: T;
        description?: T;
        checklistItems?:
          | T
          | {
              item?: T;
              category?: T;
              required?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}